# Generated by Django 6.0.4 on 2026-05-03 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор для API', unique=True, verbose_name='UUID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Анонимная сессия пользователя, добавившего запись', max_length=40, verbose_name='Ключ сессии')),
                ('name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('rank', models.CharField(blank=True, max_length=200, verbose_name='Воинское звание')),
                ('years', models.CharField(blank=True, max_length=100, verbose_name='Годы жизни')),
                ('unit', models.CharField(blank=True, max_length=300, verbose_name='Воинская часть')),
                ('award', models.CharField(blank=True, max_length=500, verbose_name='Награды')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('photo_b64', models.TextField(blank=True, default='', help_text='Фотография в формате data:image/...;base64,...', verbose_name='Фото (base64)')),
                ('approved', models.BooleanField(db_index=True, default=False, help_text='Только одобренные записи видны всем пользователям', verbose_name='Одобрено')),
                ('spell_errors', models.JSONField(blank=True, default=list, help_text='Список слов с возможными ошибками (проверяется автоматически)', verbose_name='Орфографические ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Герой войны',
                'verbose_name_plural': 'Герои войны (от пользователей)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserKhronika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('title', models.CharField(max_length=300, verbose_name='Подпись к фото')),
                ('bio', models.TextField(verbose_name='История фотографии')),
                ('section', models.CharField(choices=[('main', 'Общая хроника войны'), ('len', 'Блокада Ленинграда')], default='main', max_length=10, verbose_name='Раздел')),
                ('photo_b64', models.TextField(help_text='Фотография обязательна', verbose_name='Фото (base64)')),
                ('approved', models.BooleanField(db_index=True, default=False, verbose_name='Одобрено')),
                ('spell_errors', models.JSONField(blank=True, default=list, verbose_name='Орфографические ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Фото хроники',
                'verbose_name_plural': 'Фото хроники (от пользователей)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='Год письма')),
                ('sender', models.CharField(max_length=200, verbose_name='Автор письма')),
                ('to_person', models.CharField(blank=True, max_length=200, verbose_name='Кому адресовано')),
                ('text', models.TextField(verbose_name='Текст письма')),
                ('approved', models.BooleanField(db_index=True, default=False, verbose_name='Одобрено')),
                ('spell_errors', models.JSONField(blank=True, default=list, verbose_name='Орфографические ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Письмо с фронта',
                'verbose_name_plural': 'Письма с фронта (от пользователей)',
                'ordering': ['-created_at'],
            },
        ),
    ]
